OR.SisProductoWeb/Controllers/CompraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OR.SisProductosBL;
using OR.SisProductosEN;
using static OR.SisProductosEN.CompraEN;

namespace OR.SisProductos.Controllers
{
    public class CompraController : Controller
    {
        readonly ProveedorBL proveedorBL;
        readonly CompraBL compraBL;
        readonly ProductoBL productoBL;
        
            public CompraController(ProveedorBL pProveedorBL, CompraBL pCompraBL, ProductoBL pProductoBL)
        {
            proveedorBL = pProveedorBL;
            compraBL = pCompraBL;
            productoBL = pProductoBL;
        }

        // GET: CompraController
        public async Task<IActionResult> Index(byte? estado)
        {
            var compras = await compraBL.ObtenerPorEstadoAsync(estado ?? 0);

            var estados = new List<SelectListItem>
            {
                new SelectListItem { Value = "", Text = "Todos" },
                new SelectListItem { Value = "1", Text = "Activa" },
                new SelectListItem { Value = "2", Text = "Anulada" }
            };
            ViewBag.Estados = new SelectList(estados, "Value", "Text", estado?.ToString());

            return View(compras);
        }

        // GET: CompraController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CompraController/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Proveedores = new SelectList(await proveedorBL.ObtenerTodoAsync(), "Id", "Nombre");
            ViewBag.Productos = await productoBL.ObtenerTodosAsync();

            return View();
        }

        // POST: CompraController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CompraEN compra)
        {
            try
            {
                compra.Estado = (byte)EnumEstadoCompra.Activa;
                compra.FechaCompra = DateTime.Now;
                await compraBL.CrearAsync(compra);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CompraController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CompraController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CompraController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CompraController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> Anular(int id)
        {
            var compra = await compraBL.ObtenerPorIdAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            await compraBL.AnularAsync(id);

            return RedirectToAction("Index");
        }
    }
}

OR.SisProductoWeb/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using OR.SisProductosBL;
using OR.SisProductosEN;
using Rotativa.AspNetCore;

namespace OR.SisProductos.Controllers
{
    public class ProveedorController : Controller
    {
        readonly ProveedorBL _proveedorBL;
        public ProveedorController(ProveedorBL proveedorBL)
        {
            _proveedorBL = proveedorBL;
        }

        // GET: ProveedorController
        public async Task<ActionResult> Index()
        {
            var Proveerdores = await _proveedorBL.ObtenerTodoAsync();
            return View(Proveerdores);
        }

        // GET: ProveedorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProveedorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProveedorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ProveedorEN pProveedor)
        {
            try
            {
                var result = await _proveedorBL.CrearAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
    }
        // GET: ProveedorController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var proveedor = await _proveedorBL.ObtenerPorIdAsync(new ProveedorEN { Id = id });
            return View(proveedor);
        }

        // POST: ProveedorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ProveedorEN pProveedor)
        {
            try
            {
                var result = await _proveedorBL.ModificarAsync(pProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var proveedor = await _proveedorBL.ObtenerPorIdAsync(new ProveedorEN { Id = id });
            return View(proveedor);
        }
        // POST: ProveedorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteProveedor(int id)
        {
            try
            {
                var result = await _proveedorBL.EliminarAsync(new ProveedorEN { Id = id });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public async Task<IActionResult> ReporteProveedores()
        {
            var proveedores = await _proveedorBL.ObtenerTodoAsync();
            return new ViewAsPdf("rpProveedores", proveedores);
        }


        // Método para exportar a Excel los proveedores
        public async Task<IActionResult> ReporteProveedoresExcel()
        {
            var proveedores = await _proveedorBL.ObtenerTodoAsync();
            using (var package = new ExcelPackage())
            {
                var hojaExcel = package.Workbook.Worksheets.Add("Proveedores");
                hojaExcel.Cells["A1"].Value = "Nombre";
                hojaExcel.Cells["B1"].Value = "NRC";
                hojaExcel.Cells["C1"].Value = "Dirección";
                hojaExcel.Cells["D1"].Value = "Teléfono";
                hojaExcel.Cells["E1"].Value = "Email";

                int row = 2;
                foreach (var proveedor in proveedores)
                {
                    hojaExcel.Cells[row, 1].Value = proveedor.Nombre;
                    hojaExcel.Cells[row, 2].Value = proveedor.NRC;
                    hojaExcel.Cells[row, 3].Value = proveedor.Direccion;
                    hojaExcel.Cells[row, 4].Value = proveedor.Telefono;
                    hojaExcel.Cells[row, 5].Value = proveedor.Email;
                    row++;
                }

                hojaExcel.Cells["A:E"].AutoFitColumns();

                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Position = 0;

                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReporteProveedoresExcel.xlsx");
            }
        }

        // Método para subir un archivo Excel de proveedores  
        public async Task<IActionResult> SubirExcelProveedores(IFormFile archivoExcel)
        {
            if (archivoExcel == null || archivoExcel.Length == 0)
            {
                return RedirectToAction("Index");
            }

            var proveedores = new List<ProveedorEN>();

            using (var stream = new MemoryStream())
            {
                await archivoExcel.CopyToAsync(stream);
                using (var package = new ExcelPackage(stream))
                {
                    var hojaExcel = package.Workbook.Worksheets[0];
                    int rowCount = hojaExcel.Dimension.Rows;

                    for (int row = 2; row <= rowCount; row++)
                    {
                        var nombre = hojaExcel.Cells[row, 1].Text;
                        var nrc = hojaExcel.Cells[row, 2].Text;
                        var direccion = hojaExcel.Cells[row, 3].Text;
                        var telefono = hojaExcel.Cells[row, 4].Text;
                        var email = hojaExcel.Cells[row, 5].Text;

                        // Validar campos  
                        if (string.IsNullOrEmpty(nombre) || string.IsNullOrEmpty(nrc) || string.IsNullOrEmpty(direccion))
                            continue;

                        proveedores.Add(new ProveedorEN
                        {
                            Nombre = nombre,
                            NRC = nrc,
                            Direccion = direccion,
                            Telefono = telefono,
                            Email = email,
                        });
                    }
                }
            }

            if (proveedores.Count > 0)
            {
                await _proveedorBL.AgregarTodosAsync(proveedores);
            }
            return RedirectToAction("Index");
        }
    }
}

OR.SisProductoWeb/Controllers/VentaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OR.SisProductos.EN.Filtros;
using OfficeOpenXml;
using OR.SisProductosBL;
using OR.SisProductosEN;
using Rotativa.AspNetCore;
using static OR.SisProductos.EN.Filtros.VentaFiltros;

namespace OR.SisProductosEN
{
    public class VentaController : Controller
    {
        readonly ClienteBL clienteBL;
        readonly VentaBL ventaBL;
        readonly ProductoBL productoBL;

        public VentaController(ClienteBL pClienteBL, VentaBL pVentaBL, ProductoBL pProductoBL)
        {
            clienteBL = pClienteBL;
            ventaBL = pVentaBL;
            productoBL = pProductoBL;
        }
        // GET: VentaController
        public async Task<IActionResult> Index(byte? estado)
        {
            var ventas = await ventaBL.ObtenerPorEstadoAsync(estado ?? 0);

            var estados = new List<SelectListItem>
            {
                new SelectListItem { Value = "", Text = "Todos" },
                new SelectListItem { Value = "1", Text = "Activa" },
                new SelectListItem { Value = "2", Text = "Anulada" }
            };

            ViewBag.Estados = new SelectList(estados, "Value", "Text", estado?.ToString());

            return View(ventas);
        }

        // GET: VentaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VentaController/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Clientes = new SelectList(await clienteBL.ObtenerTodosAsync(), "Id", "Nombre");
            ViewBag.Productos = await productoBL.ObtenerTodosAsync();
            return View();
        }

        // POST: VentaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Venta venta)
        {
            try
            {
                venta.Estado = (byte)SisProductosEN.Venta.EnumEstadoVenta.Activa;
                venta.FechaVenta = DateTime.Now;
                await ventaBL.CrearAsync(venta);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VentaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VentaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VentaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VentaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public async Task<IActionResult> Anular(int id)
        {
            var venta = await ventaBL.ObtenerPorIdAsync(id);
            if (venta == null)
            {
                return NotFound();
            }

            await ventaBL.AnularAsync(id);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ReporteVentasExcel(List<Venta> ventas)
        {
            using (var package = new ExcelPackage())
            {
                var hojaExcel = package.Workbook.Worksheets.Add("Reporte Ventas");

                // Encabezados  
                hojaExcel.Cells["A1"].Value = "Fecha de Venta";
                hojaExcel.Cells["B1"].Value = "Cliente";
                hojaExcel.Cells["C1"].Value = "Producto";
                hojaExcel.Cells["D1"].Value = "Cantidad";
                hojaExcel.Cells["E1"].Value = "Subtotal";
                hojaExcel.Cells["F1"].Value = "Total de la Venta";

                int row = 2;
                int totalCantidad = 0;
                decimal totalSubtotal = 0;
                decimal totalGeneral = 0;

                foreach (var venta in ventas)
                {
                    foreach (var detalle in venta.DetalleVentas)
                    {
                        hojaExcel.Cells[row, 1].Value = venta.FechaVenta.ToString("yyyy-MM-dd");
                        hojaExcel.Cells[row, 2].Value = venta.Cliente?.Nombre ?? "N/A";
                        hojaExcel.Cells[row, 3].Value = detalle.Producto?.Nombre ?? "N/A";
                        hojaExcel.Cells[row, 4].Value = detalle.Cantidad;
                        hojaExcel.Cells[row, 5].Value = detalle.SubTotal;
                        hojaExcel.Cells[row, 6].Value = venta.Total;

                        // Acumular totales  
                        totalCantidad += detalle.Cantidad;
                        totalSubtotal += detalle.SubTotal;
                        totalGeneral += venta.Total;

                        row++;
                    }
                }

                // Fila de totales  
                hojaExcel.Cells[row, 3].Value = "Totales";
                hojaExcel.Cells[row, 4].Value = totalCantidad;
                hojaExcel.Cells[row, 5].Value = totalSubtotal;
                hojaExcel.Cells[row, 6].Value = totalGeneral;

                // Negrita para la fila de totales  
                hojaExcel.Cells[row, 3, row, 6].Style.Font.Bold = true;

                hojaExcel.Cells["A:F"].AutoFitColumns();

                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Position = 0;
                return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReporteVentasExcel.xlsx");
            }
        }
        [HttpGet]
        public async Task<IActionResult> DescargarReporte(VentaFiltros filtro)
        {
            var ventas = await ventaBL.ObtenerReporteVentasAsync(filtro);

            if (filtro.TipoReporte == (byte)EnumTipoReporte.PDF)
            {
                return new ViewAsPdf("rpVentas", ventas);
            }
            else if (filtro.TipoReporte == (byte)EnumTipoReporte.Excel)
            {
                return await ReporteVentasExcel(ventas);
            }

            return BadRequest("Formato no válido");
        }
        [HttpGet]
        public IActionResult ReporteVentas()
        {
            return View();
        }
    }
}

OR.SisProductoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>  
<html lang="es"> <!-- Cambié a "es" por si la mayoría de tu contenido está en español. -->  
<head>  
    <meta charset="utf-8" />  
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
    <title>@ViewData["Title"] - OR.SysProductos.WebApp</title>  
    
    <!-- Asegúrate de que las rutas son correctas -->  
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />  
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/OR.SysProductos.WebApp.styles.css" asp-append-version="true" />  
</head>  
<body>  
    <header>  
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">  
            <div class="container-fluid">  
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OR.SysProductos.WebApp</a>  
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"   
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">  
                    <span class="navbar-toggler-icon"></span>  
                </button>  
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">  
                    <ul class="navbar-nav flex-grow-1">  
                    @*     <li class="nav-item">  
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>  
                        </li>  
                        <li class="nav-item">  
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>  
                        *@
                            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra">Compra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor">Proveedores</a>
                        </li>
                        <li class="nav-item">  
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto">Productos</a>  
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta">Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="ReporteVentas">Reporte Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compra" asp-action="ReporteCompras">Reporte de Compras</a>
                        </li>
                    </ul>  
                </div>  
            </div>  
        </nav>  
    </header>  
    
    <div class="container">  
        <main role="main" class="pb-3">  
            @RenderBody() <!-- Aquí se cargará el contenido de las vistas específicas -->  
        </main>  
    </div>  

    <footer class="border-top footer text-muted">  
        <div class="container">  
            &copy; 2025 - OR.SysProductos.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>  
        </div>  
    </footer>  
    
    <!-- Scripts -->  
    <script src="~/lib/Chart.Js/chart.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>  
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>  
    <script src="~/js/site.js" asp-append-version="true"></script>  
    
    @await RenderSectionAsync("Scripts", required: false) <!-- Esto permite cargar scripts personalizados en las vistas. -->  
</body>  
</html>  